version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:secret@postgres:5432/authdb?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - ./auth-service:/app

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:secret@postgres:5432/customerdb?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - ./customer-service:/app

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
